# Generated by Django 4.2.19 on 2025-06-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notatki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notatka',
            name='przedmiot',
            field=models.CharField(default='Brak', max_length=200),
            preserve_default=False,
        ),
    ]
