# Generated by Django 4.2.19 on 2025-06-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notatki', '0002_notatka_przedmiot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notatka',
            name='przedmiot',
            field=models.CharField(default='Brak', max_length=100),
        ),
    ]
