# Generated by Django 4.2.19 on 2025-06-02 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notatki', '0003_alter_notatka_przedmiot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notatka',
            name='data_utworzenia',
        ),
        migrations.AddField(
            model_name='notatka',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
