# Generated by Django 4.2.19 on 2025-06-16 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notatki', '0004_remove_notatka_data_utworzenia_notatka_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notatka',
            options={'ordering': ['-data'], 'verbose_name': 'Notatka', 'verbose_name_plural': 'Notatki'},
        ),
        migrations.AddField(
            model_name='notatka',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
